### ISSUE TITLE
Possible to add custom rule support?

### ISSUE THREAD

**Issue by straker** [linthtml/linthtml#240]
I was wondering if you'd be interested in allowing custom rules. The Legacy Linter allowed custom rules through the `Config` but the Linter takes the list of rules directly from the directory. I'd be happy to write a PR if that's something you'd be interested in.

**Comment by KamiKillertO** [comment]
I'm planning on adding a plugin system like Eslint, Stylelint in v0.7.0.
I've disabled the possibility to define custom rules because the feature was not documented and I wanted to improve rules definition, name convention, inline configuration, configurations... before.
But, if you have some ideas feel free to open a PR and I'll have a look 👍.

**Comment by straker** [comment]
Awesome. If you're planning on adding it for v0.7 then I can wait for it.

**Comment by KamiKillertO** [comment]
@straker Sorry for the long wait. The plugins feature did not land on the v0.7.0 release but will land in the next release (0.8.0).
I'll release the first beta today, so if you are still interested, please have a look ^^.
