### ISSUE TITLE
[rule] indent-delta & indent-width-cont

### ISSUE THREAD

**Issue by acalvo** [linthtml/linthtml#62]
I'm quite sure `indent-delta` rule isn't used anymore as it doesn't make sense anymore after your refactor. If that's the case, could you delete the references to it across the project (and maybe document it in the "htmllint migration" section of your README)?

I'm not so sure about `indent-width-cont`. Does it still apply?

**Comment by KamiKillertO** [comment]
The rules `indent-delta` and `indent-width-cont` still exist but don't report any error anymore.
LintHTML should stay compatible with HTMLLINT until the v1 release. In order to do so I cannot remove rules, but in can flag rules as deprecated and display warning messages. This should be done in the coming v0.3 🤞.

Do you use `indent-width-cont` ? I can't find a good reason to keep this rule 🤷‍♂.

**Comment by acalvo** [comment]
> LintHTML should stay compatible with HTMLLINT until the v1 release. In order to do so I cannot remove rules, but in can flag rules as deprecated and display warning messages. This should be done in the coming v0.3 🤞.

Oh, OK. Sound good!

> Maybe a good start can be to flag the rule as deprecated in the docs. You can open a PR for this if you want.

OK! Give me some time so that I can migrate all our projects to LintHTML so that I can have a better understanding of the project and meanwhile arise oddities and/or things to improve.

> Do you use indent-width-cont ? I can't find a good reason to keep this rule 🤷‍♂.

I do use it in one of our projects... but having a look at it, seems more like a workaround for another problem. Tried LintHTML in that project and found another matter. Will report it now 😅😂
